package Ivin.HW6.DB.DAO;

import Ivin.HW6.DB.MODEL.Classes;
import Ivin.HW6.DB.MODEL.ClassesEx;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface CatMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table categories
     *
     * @mbg.generated Fri Jun 10 17:31:50 MSK 2022
     */
    long countByExample(ClassesEx example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table categories
     *
     * @mbg.generated Fri Jun 10 17:31:50 MSK 2022
     */
    int deleteByExample(ClassesEx example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table categories
     *
     * @mbg.generated Fri Jun 10 17:31:50 MSK 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table categories
     *
     * @mbg.generated Fri Jun 10 17:31:50 MSK 2022
     */
    int insert(Classes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table categories
     *
     * @mbg.generated Fri Jun 10 17:31:50 MSK 2022
     */
    int insertSelective(Classes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table categories
     *
     * @mbg.generated Fri Jun 10 17:31:50 MSK 2022
     */
    List<Classes> selectByExample(ClassesEx example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table categories
     *
     * @mbg.generated Fri Jun 10 17:31:50 MSK 2022
     */
    Classes selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table categories
     *
     * @mbg.generated Fri Jun 10 17:31:50 MSK 2022
     */
    int updateByExampleSelective(@Param("record") Classes record, @Param("example") ClassesEx example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table categories
     *
     * @mbg.generated Fri Jun 10 17:31:50 MSK 2022
     */
    int updateByExample(@Param("record") Classes record, @Param("example") ClassesEx example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table categories
     *
     * @mbg.generated Fri Jun 10 17:31:50 MSK 2022
     */
    int updateByPrimaryKeySelective(Classes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table categories
     *
     * @mbg.generated Fri Jun 10 17:31:50 MSK 2022
     */
    int updateByPrimaryKey(Classes record);
}